[package]
name = "pust"
version = "0.1.0"
authors = ["marek counts <countsmarek@gmail.com>"]

[lib]
name = "pustlib"
path = "src/lib.rs"

[[bin]]
name = "pust"
path = "src/bin/main.rs"

[dependencies]
pnet = "0.21.0"
rand = "0.3.15"
pnet_datalink = "0.21.0"
